---
downloads: ~/.ansible-downloads/

configure_sudoers: yes

dotfiles_repo: https://github.com/viscat/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/dotfiles
dotfiles_files:
  - .gitconfig
  - .inputrc
  - .vimrc

oh_my_zsh_theme: sorin

phpstorm_version        : 2017.1.3
phpstorm_install_dir    : /opt
phpstorm_bin            : /usr/local/bin/phpstorm


packages:
  - terminator
  - bash-completion
  - gpg
  - httpie
  - nmap
  - npm
  - openssl
  - wget
  - vagrant
  - virtualbox
