---
- hosts: all
  connection: local
  become: true

  vars_files:
    - config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml

  roles:
    - role: geerlingguy.git
    - role: geerlingguy.dotfiles
    - role: markushartman.phpstorm 
    - role: jdauphant.sublimetext
    - role: gantsign.oh-my-zsh
      users:
        - username: gerard

  tasks:
    - include: tasks/ansible-setup.yml
    - include: tasks/vim-config.yml
    - include: tasks/install-packages.yml
